// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.DatabaseContext;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(TeacherPupilContexts))]
    [Migration("20230319095830_firstmigration")]
    partial class firstmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.15");

            modelBuilder.Entity("WebApplication1.Entities.Pupil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TeachedId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Pupil");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Class = "5A",
                            LastName = "Smith",
                            Name = "Alice",
                            Sex = "Female",
                            TeachedId = 0
                        },
                        new
                        {
                            Id = 2,
                            Class = "5A",
                            LastName = "Johnson",
                            Name = "Bob",
                            Sex = "Male",
                            TeachedId = 0
                        },
                        new
                        {
                            Id = 3,
                            Class = "5B",
                            LastName = "Williams",
                            Name = "Charlie",
                            Sex = "Male",
                            TeachedId = 0
                        },
                        new
                        {
                            Id = 4,
                            Class = "5B",
                            LastName = "Miller",
                            Name = "Diana",
                            Sex = "Female",
                            TeachedId = 0
                        },
                        new
                        {
                            Id = 5,
                            Class = "5C",
                            LastName = "Brown",
                            Name = "Emily",
                            Sex = "Female",
                            TeachedId = 0
                        },
                        new
                        {
                            Id = 6,
                            Class = "5C",
                            LastName = "Davis",
                            Name = "Frank",
                            Sex = "Male",
                            TeachedId = 0
                        },
                        new
                        {
                            Id = 7,
                            Class = "5D",
                            LastName = "Garcia",
                            Name = "Grace",
                            Sex = "Female",
                            TeachedId = 0
                        },
                        new
                        {
                            Id = 8,
                            Class = "5D",
                            LastName = "Taylor",
                            Name = "Henry",
                            Sex = "Male",
                            TeachedId = 0
                        });
                });

            modelBuilder.Entity("WebApplication1.Entities.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teacher");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastName = "Doe",
                            Name = "John",
                            Sex = "Male",
                            Subject = "Math"
                        },
                        new
                        {
                            Id = 2,
                            LastName = "Doe",
                            Name = "Jane",
                            Sex = "Female",
                            Subject = "English"
                        },
                        new
                        {
                            Id = 3,
                            LastName = "Smith",
                            Name = "Bob",
                            Sex = "Male",
                            Subject = "Science"
                        },
                        new
                        {
                            Id = 4,
                            LastName = "Johnson",
                            Name = "Mary",
                            Sex = "Female",
                            Subject = "History"
                        },
                        new
                        {
                            Id = 5,
                            LastName = "Williams",
                            Name = "Tom",
                            Sex = "Male",
                            Subject = "Art"
                        });
                });

            modelBuilder.Entity("WebApplication1.Entities.TeacherPupil", b =>
                {
                    b.Property<int>("PupilId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PupilId", "TeacherId");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherPupil");

                    b.HasData(
                        new
                        {
                            PupilId = 1,
                            TeacherId = 2
                        },
                        new
                        {
                            PupilId = 1,
                            TeacherId = 4
                        },
                        new
                        {
                            PupilId = 2,
                            TeacherId = 1
                        },
                        new
                        {
                            PupilId = 2,
                            TeacherId = 5
                        },
                        new
                        {
                            PupilId = 2,
                            TeacherId = 6
                        },
                        new
                        {
                            PupilId = 3,
                            TeacherId = 2
                        },
                        new
                        {
                            PupilId = 3,
                            TeacherId = 3
                        },
                        new
                        {
                            PupilId = 3,
                            TeacherId = 5
                        },
                        new
                        {
                            PupilId = 4,
                            TeacherId = 5
                        },
                        new
                        {
                            PupilId = 4,
                            TeacherId = 7
                        },
                        new
                        {
                            PupilId = 5,
                            TeacherId = 1
                        },
                        new
                        {
                            PupilId = 5,
                            TeacherId = 3
                        },
                        new
                        {
                            PupilId = 5,
                            TeacherId = 8
                        });
                });

            modelBuilder.Entity("WebApplication1.Entities.TeacherPupil", b =>
                {
                    b.HasOne("WebApplication1.Entities.Pupil", "Pupil")
                        .WithMany()
                        .HasForeignKey("PupilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Entities.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pupil");

                    b.Navigation("Teacher");
                });
#pragma warning restore 612, 618
        }
    }
}
